CFLAGS = -Wall -g -std=c99 -D _POSIX_C_SOURCE=200809L -Werror

all: build

build:
	gcc $(CFLAGS) main.c receiver.c -lpthread -o main

run: build
	./main

valgrind: build
	valgrind --leak-check=full ./main
clean:
	rm -f main